grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 2
    verbose: 3
model_selection:
  module_0:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 100
    search_param_grid:
      n_estimators:
      - 100
      - 200
      - 300
      max_depth:
      - null
      - 10
      - 20
      - 30

  module_1:
    class: KNeighborsRegressor
    module: sklearn.neighbors
    search_param_grid:
      n_neighbors:
      - 3
      - 5
      - 7
      - 9
      weights:
      - uniform
      - distance
      algorithm:
      - auto
      - ball_tree
      - kd_tree
      - brute
